### ISSUE TITLE
async 

### ISSUE THREAD

**Issue by Patres1839** [esx-framework/async#8]
hi i have a problem from async i would need to help them that you even look at the error of it and would help fix it by sending me that part of that error fixed because it is not an error on my part but on the side of this script created thank you? @BrakingESX247 
![2020-08-23 (2)](https://user-images.githubusercontent.com/70112939/91046938-936a2780-e619-11ea-8e94-7d0a73f12fa7.png)
![2020-08-24](https://user-images.githubusercontent.com/70112939/91047062-c7454d00-e619-11ea-8b12-b6c345942b05.png)

**Comment by BrakingESX247** [comment]
That's not an issue with ASync. You are probably using ESX 2 master branch, get the develop one. If you need further support, get on the discord.
